export const mockData = [
  {
    id: "g2PZEG-5Azhyh834AUMFZQ",
    alias: "in-n-out-burger-arroyo-grande",
    name: "In-N-Out Burger",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/isEfE_4IcyUAYIloRYaguA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/in-n-out-burger-arroyo-grande?adjust_creative=4MDuSotUIQrL5s3qQONwPA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=4MDuSotUIQrL5s3qQONwPA",
    review_count: 215,
    categories: [
      {
        alias: "hotdogs",
        title: "Fast Food",
      },
      {
        alias: "burgers",
        title: "Burgers",
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 35.1272684,
      longitude: -120.5979198,
    },
    transactions: [],
    price: "$",
    location: {
      address1: "1170 W Branch St",
      address2: "",
      address3: "",
      city: "Arroyo Grande",
      zip_code: "93420",
      country: "US",
      state: "CA",
      display_address: ["1170 W Branch St", "Arroyo Grande, CA 93420"],
    },
    phone: "+18007861000",
    display_phone: "(800) 786-1000",
    distance: 16829.955261175728,
    business_hours: [
      {
        open: [
          {
            is_overnight: true,
            start: "1030",
            end: "0100",
            day: 0,
          },
          {
            is_overnight: true,
            start: "1030",
            end: "0100",
            day: 1,
          },
          {
            is_overnight: true,
            start: "1030",
            end: "0100",
            day: 2,
          },
          {
            is_overnight: true,
            start: "1030",
            end: "0100",
            day: 3,
          },
          {
            is_overnight: true,
            start: "1030",
            end: "0130",
            day: 4,
          },
          {
            is_overnight: true,
            start: "1030",
            end: "0130",
            day: 5,
          },
          {
            is_overnight: true,
            start: "1030",
            end: "0100",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "http://www.in-n-out.com/menu.aspx",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "_q_lPi7HBUd3HIrSAHcrnA",
    alias: "the-habit-burger-grill-san-luis-obispo",
    name: "The Habit Burger Grill",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/SrvGby_oLkCQtT2Ve8aFtw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/the-habit-burger-grill-san-luis-obispo?adjust_creative=4MDuSotUIQrL5s3qQONwPA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=4MDuSotUIQrL5s3qQONwPA",
    review_count: 279,
    categories: [
      {
        alias: "burgers",
        title: "Burgers",
      },
      {
        alias: "sandwiches",
        title: "Sandwiches",
      },
      {
        alias: "salad",
        title: "Salad",
      },
    ],
    rating: 3.5,
    coordinates: {
      latitude: 35.2800479,
      longitude: -120.6623576,
    },
    transactions: ["pickup", "delivery"],
    price: "$",
    location: {
      address1: "839 Higuera St",
      address2: "",
      address3: "",
      city: "San Luis Obispo",
      zip_code: "93401",
      country: "US",
      state: "CA",
      display_address: ["839 Higuera St", "San Luis Obispo, CA 93401"],
    },
    phone: "+18055420105",
    display_phone: "(805) 542-0105",
    distance: 1245.4650949321538,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1030",
            end: "2200",
            day: 0,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "2200",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "2200",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "2200",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "2200",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "2200",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "2130",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "https://www.habitburger.com/menu/",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "2Np_uaqExTpCdK3CrgTSXQ",
    alias: "five-guys-san-luis-obispo-2",
    name: "Five Guys",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/CiR8PLPjf33fCEHuIZIaJA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/five-guys-san-luis-obispo-2?adjust_creative=4MDuSotUIQrL5s3qQONwPA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=4MDuSotUIQrL5s3qQONwPA",
    review_count: 92,
    categories: [
      {
        alias: "hotdogs",
        title: "Fast Food",
      },
      {
        alias: "burgers",
        title: "Burgers",
      },
      {
        alias: "hotdog",
        title: "Hot Dogs",
      },
    ],
    rating: 3.1,
    coordinates: {
      latitude: 35.293883473819754,
      longitude: -120.67317633618352,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "763 E Foothill Blvd",
      address2: "",
      address3: null,
      city: "San Luis Obispo",
      zip_code: "93405",
      country: "US",
      state: "CA",
      display_address: ["763 E Foothill Blvd", "San Luis Obispo, CA 93405"],
    },
    phone: "+18054393622",
    display_phone: "(805) 439-3622",
    distance: 2927.0597584014445,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 0,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "https://www.fiveguys.com/menu",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "fJJ5Vv1pWF4VMIP99TYqgA",
    alias: "chick-fil-a-san-luis-obispo",
    name: "Chick-fil-A",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/hL3Xbd0fl3n57FMqTyLzRw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/chick-fil-a-san-luis-obispo?adjust_creative=4MDuSotUIQrL5s3qQONwPA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=4MDuSotUIQrL5s3qQONwPA",
    review_count: 15,
    categories: [
      {
        alias: "hotdogs",
        title: "Fast Food",
      },
      {
        alias: "chickenshop",
        title: "Chicken Shop",
      },
      {
        alias: "salad",
        title: "Salad",
      },
    ],
    rating: 3.7,
    coordinates: {
      latitude: 35.29962355083653,
      longitude: -120.65970508580595,
    },
    transactions: [],
    price: "$",
    location: {
      address1: "1901 Marketplace",
      address2: "Bldg 19",
      address3: null,
      city: "San Luis Obispo",
      zip_code: "93407",
      country: "US",
      state: "CA",
      display_address: [
        "1901 Marketplace",
        "Bldg 19",
        "San Luis Obispo, CA 93407",
      ],
    },
    phone: "+18057565952",
    display_phone: "(805) 756-5952",
    distance: 3474.2330355332374,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1030",
            end: "1600",
            day: 0,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "1600",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "1600",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "2100",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "1600",
            day: 4,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "https://www.chick-fil-a.com/menu",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "_2NkRMVyj5tOTPiKA8j-5Q",
    alias: "brooks-burgers-san-luis-obispo",
    name: "Brooks Burgers",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/oZgWMNDiZznrqXFklVqp6A/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/brooks-burgers-san-luis-obispo?adjust_creative=4MDuSotUIQrL5s3qQONwPA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=4MDuSotUIQrL5s3qQONwPA",
    review_count: 91,
    categories: [
      {
        alias: "burgers",
        title: "Burgers",
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 35.24715292077206,
      longitude: -120.671570802472,
    },
    transactions: ["pickup", "delivery"],
    location: {
      address1: "34 Tank Farm Rd",
      address2: "",
      address3: null,
      city: "San Luis Obispo",
      zip_code: "93401",
      country: "US",
      state: "CA",
      display_address: ["34 Tank Farm Rd", "San Luis Obispo, CA 93401"],
    },
    phone: "",
    display_phone: "",
    distance: 2476.2008889082804,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1100",
            end: "2000",
            day: 0,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2000",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2000",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2000",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2000",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2000",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2000",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "https://www.brooksburgersca.com/menu-san-luis-obispo",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "umvmHgAFJeq9YzIcSWx-ZQ",
    alias: "eddies-grill-san-luis-obispo",
    name: "Eddie's Grill",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/PetVJwmhnGGbZVGt2TaU5w/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/eddies-grill-san-luis-obispo?adjust_creative=4MDuSotUIQrL5s3qQONwPA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=4MDuSotUIQrL5s3qQONwPA",
    review_count: 167,
    categories: [
      {
        alias: "burgers",
        title: "Burgers",
      },
      {
        alias: "sandwiches",
        title: "Sandwiches",
      },
      {
        alias: "juicebars",
        title: "Juice Bars & Smoothies",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 35.2611409193444,
      longitude: -120.649054670033,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "3212 Broad St",
      address2: "Ste 120",
      address3: null,
      city: "San Luis Obispo",
      zip_code: "93401",
      country: "US",
      state: "CA",
      display_address: [
        "3212 Broad St",
        "Ste 120",
        "San Luis Obispo, CA 93401",
      ],
    },
    phone: "+18057521228",
    display_phone: "(805) 752-1228",
    distance: 1606.7993837983347,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "0800",
            end: "2000",
            day: 0,
          },
          {
            is_overnight: false,
            start: "0800",
            end: "2000",
            day: 1,
          },
          {
            is_overnight: false,
            start: "0800",
            end: "2000",
            day: 2,
          },
          {
            is_overnight: false,
            start: "0800",
            end: "2000",
            day: 3,
          },
          {
            is_overnight: false,
            start: "0800",
            end: "2000",
            day: 4,
          },
          {
            is_overnight: false,
            start: "0800",
            end: "2000",
            day: 5,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: null,
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "kTky-x9NBHYzD0F981-K9A",
    alias: "burger-village-san-luis-obispo",
    name: "Burger Village",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/hydjWQZ9A7WkUpKtRjF6Aw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/burger-village-san-luis-obispo?adjust_creative=4MDuSotUIQrL5s3qQONwPA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=4MDuSotUIQrL5s3qQONwPA",
    review_count: 451,
    categories: [
      {
        alias: "burgers",
        title: "Burgers",
      },
      {
        alias: "beerbar",
        title: "Beer Bar",
      },
      {
        alias: "salad",
        title: "Salad",
      },
    ],
    rating: 3.8,
    coordinates: {
      latitude: 35.27901,
      longitude: -120.66475,
    },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "698 Higuera St",
      address2: "",
      address3: null,
      city: "San Luis Obispo",
      zip_code: "93401",
      country: "US",
      state: "CA",
      display_address: ["698 Higuera St", "San Luis Obispo, CA 93401"],
    },
    phone: "+18054391663",
    display_phone: "(805) 439-1663",
    distance: 1164.7401250576363,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 0,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "https://www.burgervillage.com/slo-california-menu/",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "-kphusYansF9UdFhpG1r5A",
    alias: "cork-n-bottle-liquor-store-and-deli-san-luis-obispo-2",
    name: "Cork 'n' Bottle Liquor Store & Deli",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/HsKPRSooFtTH6XtF98AFIQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/cork-n-bottle-liquor-store-and-deli-san-luis-obispo-2?adjust_creative=4MDuSotUIQrL5s3qQONwPA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=4MDuSotUIQrL5s3qQONwPA",
    review_count: 55,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
      {
        alias: "burgers",
        title: "Burgers",
      },
    ],
    rating: 3.3,
    coordinates: {
      latitude: 35.294532,
      longitude: -120.672256,
    },
    transactions: ["pickup", "delivery"],
    price: "$",
    location: {
      address1: "774 Foothill Blvd",
      address2: null,
      address3: "",
      city: "San Luis Obispo",
      zip_code: "93405",
      country: "US",
      state: "CA",
      display_address: ["774 Foothill Blvd", "San Luis Obispo, CA 93405"],
    },
    phone: "+18055438637",
    display_phone: "(805) 543-8637",
    distance: 2983.7001252077207,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "0700",
            end: "0000",
            day: 0,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "0000",
            day: 1,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "0000",
            day: 2,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "0000",
            day: 3,
          },
          {
            is_overnight: true,
            start: "0700",
            end: "0100",
            day: 4,
          },
          {
            is_overnight: true,
            start: "0700",
            end: "0100",
            day: 5,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "0000",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: null,
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "-sTsgXxnWSM_AhGMCVhnvg",
    alias: "carls-jr-san-luis-obispo-2",
    name: "Carl's Jr",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/gw0Wb4V9wFf-VtABk9tJeA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/carls-jr-san-luis-obispo-2?adjust_creative=4MDuSotUIQrL5s3qQONwPA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=4MDuSotUIQrL5s3qQONwPA",
    review_count: 41,
    categories: [
      {
        alias: "hotdogs",
        title: "Fast Food",
      },
      {
        alias: "burgers",
        title: "Burgers",
      },
    ],
    rating: 2.5,
    coordinates: {
      latitude: 35.2496101057634,
      longitude: -120.643389484774,
    },
    transactions: ["pickup", "delivery"],
    price: "$",
    location: {
      address1: "3980 Broad St",
      address2: "",
      address3: "",
      city: "San Luis Obispo",
      zip_code: "93401",
      country: "US",
      state: "CA",
      display_address: ["3980 Broad St", "San Luis Obispo, CA 93401"],
    },
    phone: "+18057880510",
    display_phone: "(805) 788-0510",
    distance: 2834.1881013035572,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "0700",
            end: "2300",
            day: 0,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "2100",
            day: 1,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "2100",
            day: 2,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "2100",
            day: 3,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "2100",
            day: 4,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "2100",
            day: 5,
          },
          {
            is_overnight: false,
            start: "0700",
            end: "2100",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "https://carlsjr.com/menu",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "r_BXDiUQp3bIIWG4pwqqqQ",
    alias: "mcdonalds-san-luis-obispo-2",
    name: "McDonald's",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/lMmC9wWsZWBfG54D2Qiekg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/mcdonalds-san-luis-obispo-2?adjust_creative=4MDuSotUIQrL5s3qQONwPA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=4MDuSotUIQrL5s3qQONwPA",
    review_count: 140,
    categories: [
      {
        alias: "hotdogs",
        title: "Fast Food",
      },
      {
        alias: "burgers",
        title: "Burgers",
      },
      {
        alias: "coffee",
        title: "Coffee & Tea",
      },
    ],
    rating: 2.2,
    coordinates: {
      latitude: 35.2628981718302,
      longitude: -120.677427491191,
    },
    transactions: ["delivery"],
    price: "$",
    location: {
      address1: "275 Madonna Rd",
      address2: "",
      address3: "",
      city: "San Luis Obispo",
      zip_code: "93401",
      country: "US",
      state: "CA",
      display_address: ["275 Madonna Rd", "San Luis Obispo, CA 93401"],
    },
    phone: "+18055433550",
    display_phone: "(805) 543-3550",
    distance: 1356.6086449001589,
    business_hours: [
      {
        open: [
          {
            is_overnight: true,
            start: "0000",
            end: "0000",
            day: 0,
          },
          {
            is_overnight: true,
            start: "0000",
            end: "0000",
            day: 1,
          },
          {
            is_overnight: true,
            start: "0000",
            end: "0000",
            day: 2,
          },
          {
            is_overnight: true,
            start: "0000",
            end: "0000",
            day: 3,
          },
          {
            is_overnight: true,
            start: "0000",
            end: "0000",
            day: 4,
          },
          {
            is_overnight: true,
            start: "0000",
            end: "0000",
            day: 5,
          },
          {
            is_overnight: true,
            start: "0000",
            end: "0000",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url:
        "https://www.mcdonalds.com/us/en-us/full-menu.html?cid=PS:GCM_MOP:NB::Yelp:All",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "GrZAbqWSXfqrwl6MnQBiFg",
    alias: "chipotle-mexican-grill-san-luis-obispo-2",
    name: "Chipotle Mexican Grill",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/_enIA3QbvYomHeTpsk3Taw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/chipotle-mexican-grill-san-luis-obispo-2?adjust_creative=4MDuSotUIQrL5s3qQONwPA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=4MDuSotUIQrL5s3qQONwPA",
    review_count: 263,
    categories: [
      {
        alias: "mexican",
        title: "Mexican",
      },
      {
        alias: "hotdogs",
        title: "Fast Food",
      },
    ],
    rating: 2.1,
    coordinates: {
      latitude: 35.2626158404746,
      longitude: -120.67769808497,
    },
    transactions: ["pickup", "delivery"],
    price: "$",
    location: {
      address1: "297 Madonna Rd",
      address2: "",
      address3: "",
      city: "San Luis Obispo",
      zip_code: "93405",
      country: "US",
      state: "CA",
      display_address: ["297 Madonna Rd", "San Luis Obispo, CA 93405"],
    },
    phone: "+18055416975",
    display_phone: "(805) 541-6975",
    distance: 1393.0914146511352,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1030",
            end: "2300",
            day: 0,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "2300",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "2300",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "2300",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "2300",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "2300",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1030",
            end: "2300",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "http://www.chipotle.com/menu",
      open24_hours: null,
      waitlist_reservation: null,
    },
  },
  {
    id: "IMuqXY5ynHHCgZzOI7nXPg",
    alias: "finneys-crafthouse-san-luis-obispo-san-luis-obispo",
    name: "Finneys Crafthouse - San Luis Obispo",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/srN4qo0tFD9WNamZp2Hztg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/finneys-crafthouse-san-luis-obispo-san-luis-obispo?adjust_creative=4MDuSotUIQrL5s3qQONwPA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=4MDuSotUIQrL5s3qQONwPA",
    review_count: 592,
    categories: [
      {
        alias: "newamerican",
        title: "New American",
      },
      {
        alias: "cocktailbars",
        title: "Cocktail Bars",
      },
      {
        alias: "burgers",
        title: "Burgers",
      },
    ],
    rating: 4.3,
    coordinates: {
      latitude: 35.280577,
      longitude: -120.662819,
    },
    transactions: ["pickup"],
    price: "$$",
    location: {
      address1: "857 Monterey St",
      address2: "",
      address3: null,
      city: "San Luis Obispo",
      zip_code: "93401",
      country: "US",
      state: "CA",
      display_address: ["857 Monterey St", "San Luis Obispo, CA 93401"],
    },
    phone: "+18054392556",
    display_phone: "(805) 439-2556",
    distance: 1341.4171242082616,
    business_hours: [
      {
        open: [
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 0,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 1,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 2,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 3,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 4,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2200",
            day: 5,
          },
          {
            is_overnight: false,
            start: "1100",
            end: "2100",
            day: 6,
          },
        ],
        hours_type: "REGULAR",
        is_open_now: true,
      },
    ],
    attributes: {
      business_temp_closed: null,
      menu_url: "",
      open24_hours: null,
      waitlist_reservation: true,
    },
  },
];
